### ISSUE TITLE
if repeat option for the panels are in use, they are not rendered in pdf.

### ISSUE THREAD

**Issue by Sha90** [IzakMarais/reporter#92] opened 2018-10-05 11:20 UTC
Hi,

if repeat option for the panels are in use, they are not rendered in pdf.
Only one panel is rendered (which is base).
![image](https://user-images.githubusercontent.com/14327712/46532468-dd688980-c898-11e8-934e-c01db3e792a5.png)

**Comment by IzakMarais** [comment] 2018-10-05 12:12
This is a duplicate of #55 and #79. Since the reporter uses the grafana dashboards API to get the dashboard definition, I am not sure how that is supposed to interact with templating (repeating rows). 

Currently there is no workaround for this, but I have not investigated it in detail. If you want to add more insight please comment on #79.

**Closed by IzakMarais** 2018-10-05 12:12 UTC
