### ISSUE TITLE
SSL skip verification

### ISSUE THREAD

**Issue by citiscaner** [IzakMarais/reporter#90] opened 2018-10-04 13:32 UTC
You have an interesting project and I was playing around with the docker version of the reported with K8s, but i hit into error on SSL certificate. Since i am using self signed ceritifcate, it's throwing an error on me about the cert.

[Reporter]  -- (https:\\some_ip:3000)--> [ Grafana with Auth ]
  
Am wondering if there is a way to perform SSL verification similar to performing curl -k <https://blah.blah> or workaround available around it?

Thanks

**Comment by IzakMarais** [comment] 2018-10-05 06:08
Currently the reporter does not have an insecure options (similar to curl's -k). 

Options include:
* modifying the souce code to achieve that if you wanted. It is a simple golang configuration of the http client. I would be open to accepting a PR that makes this configurable via a reporter flag. I might also do it myself when I have some time. 
* you could use https://letsencrypt.org/ to generate your SSL certificate and then ensure that it is installed in the correct place on the reporter host. See [this issue](https://github.com/IzakMarais/reporter/issues/76#issuecomment-414209461), where someone had problems caused by their certificate not being in one of the places the golang client looks for certificates

**Comment by krysalead** [comment] 2019-07-11 10:57
Pull request made
https://github.com/IzakMarais/reporter/pull/134

**Comment by IzakMarais** [comment] 2019-07-18 08:48
Closed by https://github.com/IzakMarais/reporter/pull/134

    Usage grafana-reporter -sslCheck=false

**Closed by IzakMarais** 2019-07-18 08:48 UTC
Labels: enhancement
