### ISSUE TITLE
reporter doesn't support Repeating Rows and Repeating Panels feature

### ISSUE THREAD

**Issue by LinuxGit** [IzakMarais/reporter#100] opened 2018-11-19 04:08 UTC
If grafana dashboard uses Repeating Rows and Repeating Panels features(see http://docs.grafana.org/reference/templating/), some rows and panels are dynamically genarated. But http://grafana_IP:3000/api/dashboards/db/:slug API doesn't cantain repeated rows. So exported pdf will lose some data.

I found that JSON content of `View JSON` button on the dashboard is correct, but didn't find it's API.
It seems that we need to realize the repeating logic.

Do you have any ideas? Thanks.

**Comment by IzakMarais** [comment] 2018-11-23 11:01
Hallo, yes you are correct.

This is a duplicate of #55 and #79. Since the reporter uses the grafana dashboards API to get the dashboard definition, I am not sure how that is supposed to interact with templating (repeating rows).

Currently there is no workaround for this, but I have not investigated it in detail. If you want to add more insight please comment on #79.

**Closed by IzakMarais** 2018-11-23 11:01 UTC
