### ISSUE TITLE
Feature request: table panel height 

### ISSUE THREAD

**Issue by SindhujaSoundarapandian** [IzakMarais/reporter#72] opened 2018-07-20 12:00 UTC
Hi,

I tried the below steps

1. Installed go lang and started the grafana reporter
2. Installed PDFLatex and created environment variable path
3. Provided api url as 'http://localhost:8686/api/v5/report/IUjOhkNik' in grafana dashboard and created link as document in grafana dashboard
4. when i tried to click on the doc link it throws the below error

error fetching dashboard IUjOhkNik: error obtaining dashboard from http://localhost:3000/api/dashboards/uid/IUjOhkNik?var-Suite=Suite2&var-TestTitle1=JMeter+Test&var-aggregation=30s&var-application=MyTest5&var-data_source=jmeter&var-measurement_name=jmeter&var-send_interval=5&var-transaction=Access. Got Status 401 Unauthorized, message: {"message":"Unauthorized"} 

5. I tried hitting the url seperately in browser where it retrieves the dashboard json data successfully but from grafana dashboard its always throwing 401- Unauthorized error
6. No such restrictions to access the dashboard , it has the required viewer permissions
7. Below is the log file generated in go console

2018/07/20 16:33:44 grafana reporter, version: 2.0-1 hash: 098683c4db326f42728f8d1aadc876f1e826098e
2018/07/20 16:33:44 serving at ':8686' and using grafana at 'localhost:3000'
2018/07/20 16:33:45 Reporter called
2018/07/20 16:33:45 Called with api Token:
2018/07/20 16:33:45 Called with variable: var-TestTitle1 [JMeter Test]
2018/07/20 16:33:45 Called with variable: var-aggregation [30s]
2018/07/20 16:33:45 Called with variable: var-transaction [Access]
2018/07/20 16:33:45 Called with variable: var-measurement_name [jmeter]
2018/07/20 16:33:45 Called with variable: var-send_interval [5]
2018/07/20 16:33:45 Called with variable: var-Suite [Suite2]
2018/07/20 16:33:45 Called with variable: var-data_source [jmeter]
2018/07/20 16:33:45 Called with variable: var-application [MyTest5]
2018/07/20 16:33:45 Called with dashboard: IUjOhkNik
2018/07/20 16:33:45 Called with time range: {1528966160000 1528966499000}
2018/07/20 16:33:45 Connecting to dashboard at http://localhost:3000/api/dashboards/uid/IUjOhkNik?var-Suite=Suite2&var-TestTitle1=JMeter+Test&var-aggregation=30s&var-application=MyTest5&var-data_source=jmeter&var-measurement_name=jmeter&var-send_interval=5&var-transaction=Access
2018/07/20 16:33:45 Error generating report: error fetching dashboard IUjOhkNik: error obtaining dashboard from http://localhost:3000/api/dashboards/uid/IUjOhkNik?var-Suite=Suite2&var-TestTitle1=JMeter+Test&var-aggregation=30s&var-application=MyTest5&var-data_source=jmeter&var-measurement_name=jmeter&var-send_interval=5&var-transaction=Access. Got Status 401 Unauthorized, message: {"message":"Unauthorized"}

Any help would be appreciated.

Thanks,
Sindhuja

**Comment by IzakMarais** [comment] 2018-07-20 13:46
You should generate an authorisation apitoken in the grafana user interface and pass that along as described in the readme [here](https://github.com/IzakMarais/reporter#query-parameters).

**Comment by SindhujaSoundarapandian** [comment] 2018-07-23 08:44
Thanks for your response !

It worked successfully but after generating PDF i could see some unwanted spaces in PDF and also if i have 4 tables with single row each means it was generating dashboard with 4 pages , one table per page, is there a way to reduce the page sizing or reducing the width/height to display in a proper format ?
Please help us to resolve this issue.

**Comment by IzakMarais** [comment] 2018-07-23 09:11
If you want finer control over the layout, you can write your own custom LaTeX template.

See the ['template' section under Query paramters in the readme](https://github.com/IzakMarais/reporter#query-parameters).

Here is an [example issue](https://github.com/IzakMarais/reporter/issues/50#issuecomment-378956538) where someone used a template to create landscape mode reports.

**Comment by SindhujaSoundarapandian** [comment] 2018-07-23 09:31
I could see height and width are hardcorded in your code, and from your clarifications i tried to update the height and width in json data but it was not reflected in PDF. Is there a way to edit the panel size ? can you please share your thoughts on it.[https://github.com/IzakMarais/reporter/blob/master/grafana/api.go#L160](url)

**Comment by IzakMarais** [comment] 2018-07-23 10:14
Great, so after resolving the authentication problem, it seems your remaining issue is related to (perhaps a duplicate of) https://github.com/IzakMarais/reporter/issues/52? If so, that is nice since this adds another +1 for that planned enhancement.

**Comment by IzakMarais** [comment] 2018-08-03 08:12
OK, so unfortunately the fix for #52 doesn't work here for Tables with scrolling enabled. If the table doesn't have scrolling enabled, requesting a small, say 100 pixel high, render works: it actually renders the table high enough to fit in all the rows that need to be displayed. For tables _with_ scrolling it will actually adhere to the requested height, which means the table will be rendered without adequate height in all cases. Since scrolling is on by default, this is not sufficient. 

A possible fix is to interrogate the table json and decide how high to render it based on more than just the panel type.

**Comment by IzakMarais** [comment] 2019-03-07 11:13
This feature might also help for very tall tables where the height has been modified in the dashboard to allow  many rows to be displayed on a single page.

**Comment by IzakMarais** [comment] 2019-07-18 07:23
A more concise summary of the problem from https://github.com/IzakMarais/reporter/issues/142:

> When you do a report which contains a table, then only the visible part of the table is exported to pdf. The entire result of the table query are split on many sheets that you access with clicking on number below table. The pdf report has only this visible part, not the entire table.

**Comment by IzakMarais** [comment] 2019-10-18 06:33
Partially addressed by enabling new grid-layout flag (-grid-layout=1), which will allow all the rows visible on the dashboard table panel's first page to be captured in the report PNG. 

See #162 (comment) for an example.

For tables that span multiple pages, I don't see any way to add support for those.

**Closed by IzakMarais** 2019-10-18 06:33 UTC
Labels: enhancement
