### ISSUE TITLE
Collapsed rows omitted from report generation - expected behavior?

### ISSUE THREAD

**Issue by etepsic** [IzakMarais/reporter#360] opened 2024-01-04 07:22 UTC
Dashboards containing Panels within Rows in a collapsed state seem to be omitted from reports.

I cannot seem to find reference or mention of this behavior in the repository. And it can lead to situations where the cause of 'empty' PDFs may not be obvious.

If someone can confirm this is expected behavior, I'll send a PR to include a note on it in the README.md .

**Comment by etgraylog** [comment] 2024-01-10 19:38
Please close this as duplicate of #124  .

**Closed as completed** 2024-01-28 17:47 UTC
