### ISSUE TITLE
Error with PDFTex

### ISSUE THREAD

**Issue by mikesand** [IzakMarais/reporter#11] opened 2017-06-07 15:09 UTC
Hi,

Thanks for making this. Pretty slick and solves a big problem for me. That said, I have two reports that won't work and throw the following error.

Can you point me towards any area I can start looking?

Error calling LaTeX: "exit status 1". Latex failed with output: This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./report.tex
LaTeX2e <2016/02/01>
Babel <3.9q> and hyphenation patterns for 3 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
No file report.aux.
(/usr/share/texlive/texmf-dist/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty))
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty))
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex

LaTeX Warning: No \author given.

!pdfTeX error: pdflatex (file ./images/image5.png): reading image file failed
 ==> Fatal error occurred, no output PDF file produced!

**Comment by IzakMarais** [comment] 2017-06-07 15:40
Hi mikesand, 

Glad that you find it useful. It would be great if you could help resolve this bug with a PR!

The error "reading image file failed" seems to suggest that fetching one of the panel PNGs from Grafana via its API failed. Looking at the source code, it seems this is currently a silent failure: https://github.com/IzakMarais/reporter/blob/master/report.go#L104.

The first step would be to add logging for that error; that it is missing is clearly an oversight.  Once we have a better idea of what the error is, we consider possible solutions.

**Comment by clarelewis73** [comment] 2017-06-07 15:58
Hi IzakMarais, 

I have followed your steps for the pdf reporter, but i am getting an error saying localhost refuses to connect, any chance you know of a fix? Think I've installed everything correctly, but not sure how to check that everything downloaded!

Thanks!

**Comment by IzakMarais** [comment] 2017-06-08 06:36
@clarelewis73 This seems unrelated to the error message described in this issue? If so, please open a new issue describing clearly which steps you followed and what error message you get at which step along the way.

**Comment by IzakMarais** [comment] 2017-06-19 07:00
@mikesand: Will you be able to add logging as suggested in https://github.com/IzakMarais/reporter/issues/11#issuecomment-306834890 to try to resolve this issue?

**Comment by mikesand** [comment] 2017-06-20 13:29
Hi Izak,

I actually haven't had a chance to look at it yet. The issue is I forgot
that it was in Go and I don't write Go so it's going to take me a while to
troubleshoot so I need to wait until I have a bit more time to dedicate to
it or write my own in Python.

*Regards,*

*Mike Sanders*
*Cenersys*
*www.cenersys.com <http://www.cenersys.com>*
*305 501-5140 Ext: 1005*

**Comment by IzakMarais** [comment] 2017-06-20 14:10
Hi Mike, 

I've added some error reporting and logging in the latest commit. 

Can you 
1. Pull the latest commit. 

        cd src/github.com/izakmarais/reporter
        git pull

2. rebuild and retest your problematic dashboard. The log output should give us a clue of what the cause of the problem is

**Comment by mikesand** [comment] 2017-06-20 18:04
Ok, I'll try this later today.

*Regards,*

*Mike Sanders*
*Cenersys*
*www.cenersys.com <http://www.cenersys.com>*
*305 501-5140 Ext: 1005*

**Comment by zmaktouf** [comment] 2017-07-10 09:09
I think I am missing something, I am not able to see any report.
I am always getting {"message":"Not found"}
Any step missing to deploy grafana-reporter?

Thanks!

**Comment by adityacs** [comment] 2017-09-16 07:59
@IzakMarais I have pulled the latest code and built. Still I am getting the abover error.

**Comment by IzakMarais** [comment] 2017-09-18 06:13
@zmaktouf: That seems unrelated to this issue. If you want to you can create a new issue and give more details. 

@adityacs, which error are you referring to with "the above error"? Did the log output give any clue as to why the images might be size 0?

**Comment by msteggink** [comment] 2017-09-26 06:30
This has probably something to do with #17 , it works until Piecharts are added to the report.

I can see this:

`
2017/09/26 08:26:14 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <title>Grafana - Error</title>
    <link href='/public/css/fonts.min.css' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/public/css/grafana.dark.min.ae7bca12.css">
    <link rel="icon" type="image/png" href="/public/img/fav32.png">
    <base href="/" />
  </head>
  <body>
    <div class="page-container">
      <div class="page-header">
        <h1>Server side error :(</h1>
      </div>
      <h4>Timeout error. You can set timeout in seconds with &amp;timeout url parameter</h4>

    </div>
  </body>
</html>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <title>Grafana - Error</title>
    <link href='/public/css/fonts.min.css' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/public/css/grafana.dark.min.ae7bca12.css">
    <link rel="icon" type="image/png" href="/public/img/fav32.png">
    <base href="/" />
  </head>
  <body>
    <div class="page-container">
      <div class="page-header">
        <h1>Server side error :(</h1>
      </div>
      <h4>Rendering failed.</h4>

    </div>
  </body>
</html>
`

**Comment by clarelewis73** [comment] 2017-09-28 11:45
If the image size are zero it is because they didn't get to download, see other loading panels issue. Just need to put in a delay to space or the api calls. I got mine working with a 1 second delay between calls.

Add a delay in the report.go code 
In the renderPNGsparallel function Just after the

go func (p grafana.Panel) { 

Line!

Cleared my issues up!

**Comment by throrin19** [comment] 2018-02-28 13:14
Same problem Here. I think it's great if we can change the timeout url param to request grafana

**Comment by IzakMarais** [comment] 2018-03-01 10:57
This should be fixed by commit 4adcd89a9b5da57758dc98d278eceac03adda358.

**Closed by IzakMarais** 2018-03-01 10:57 UTC
