### ISSUE TITLE
Feature request: text panel height

### ISSUE THREAD

**Issue by nuphoff** [IzakMarais/reporter#80] opened 2018-08-16 14:17 UTC
Is it possible to make the height of the rendered text panels dynamic instead of 100.
This should be possible by querying the dashboard api using the dashboard uid which will return all panels with also the 'h' and 'w' property which indicates the size of the rows and columns a panel had.

Does this feature make sense ?
I could also try to make a PR for this feature if this feature makes sense but you don't have enough time to implement it?

**Comment by IzakMarais** [comment] 2018-08-20 06:29
Why would you want to do this? What is the problem with the current solution? The 100 text height was added in the latest release in an attempt to have more dynamic text panel heights. I did a couple of tests with 100 and it seemed that the rendered text box correctly scaled (increased its height) to accommodate larger text panels. 

What you are proposing would indeed be necessary for tables, see https://github.com/IzakMarais/reporter/issues/72#issuecomment-410179915.

**Comment by nuphoff** [comment] 2018-08-20 07:59
That sounds exactly how i hoped the reporter would react for the text panels, the problem i have now is that my text panels are being cut off at I think 100px in height so when i have more then 3 lines in a text panel it wont be rendered.

![grafana-reporter-text-panel-issue](https://user-images.githubusercontent.com/4758951/44327543-3b631e00-a45f-11e8-9e1e-fcc28ab76eff.png)

I'm using the latest image of grafana and the grafana-reporter freom the docker hub.

**Comment by IzakMarais** [comment] 2018-08-20 09:41
Interesting, I have the opposite result:

![my test](https://user-images.githubusercontent.com/8266640/44332892-8c7a0e80-a46d-11e8-8118-0dfed262707c.PNG)

You can actually test this from Grafana itself (bypassing the reporter) by clicking on the panel _title -> share -> direct link rendered image_.  

My panel content is:
```
{
  "content": "# title\n\nTest text panel rendering in grafana-reporter\n\nTest text panel rendering in grafana-reporter\n\nTest text panel rendering in grafana-reporter\n\nTest text panel rendering in grafana-reporter\n\nTest text panel rendering in grafana-reporter\n\nTest text panel rendering in grafana-reporter\n\nTest text panel rendering in grafana-reporter",
  "id": 2,
  "links": [],
  "mode": "markdown",
  "span": 3,
  "title": "Panel with many rows",
  "type": "text"
}
```
Do you mind testing that on your side?

**Comment by nuphoff** [comment] 2018-08-20 10:34
I've used the direct link and then the resulting image is big enough.

![grafana-using-direct-link](https://user-images.githubusercontent.com/4758951/44335377-8fc4c880-a474-11e8-84ea-7c12fa17dd18.png)

But when i view the logs of the grafana-reporter using docker the link is different and this link contains the 100 which will make the image 100px high i think.

![grafana-using-direct-link-with-fixed-height](https://user-images.githubusercontent.com/4758951/44335594-4628ad80-a475-11e8-81e6-c784531e32ca.png)

**Comment by IzakMarais** [comment] 2018-08-20 13:27
Yes, for sure I request 100px high, but in my experience Grafana will auto increase the rendered image size of the text box:

![image](https://user-images.githubusercontent.com/8266640/44343094-45037a80-a48d-11e8-9e3a-911bf5708917.png)

Here I request a 100px high image but get a 333px high image returned. 

What Grafana version are you using? That was tested against 4.6.4. Maybe this behaviour has changed in Grafana 5. I will need to compare...

**Comment by jahluwalia** [comment] 2018-08-20 19:04
I'm running into this issue as well. Do let us know if you have a workaround or update.

**Comment by nuphoff** [comment] 2018-08-20 20:33
@IzakMarais I will verify this on Wednesday if it is caused by Grafana, thanks for the quick response.

**Comment by nuphoff** [comment] 2018-08-22 07:49
@IzakMarais Should I issue a bug report to the Grafana repository?

**Comment by IzakMarais** [comment] 2018-08-22 09:50
@nuphoff , thanks for the test. I think that I was taking a chance using such an undocumented behaviour. It is perfectly reasonable for it to behave the way it does after 5.0 release. 

The short term solution will be to roll back the dynamic image height functionality. 

In the long term something like what you suggested, where the dashboard definition is interrogated for the panel size and that size is then passed through to the render image call on the Grafana API would be best.

**Comment by nuphoff** [comment] 2018-08-22 19:48
A quick 'workaround' is not needed because we're not using the reporter in production yet so we have enough time to wait for a permanent fix.

**Comment by jahluwalia** [comment] 2018-08-22 19:52
Why can't we just not specify a height at all?

**Comment by IzakMarais** [comment] 2018-08-24 13:44
> Meaning when you don't specify a height and width, it looks like it still gets a full image. Not sure what it will look like in the pdf.

This sounds like a great fix! Can you confirm that this is the behaviour in Grafana 5. (I'm a bit busy now so don't have time to set up a test Grafana 5 instance). It seems to work nicely in Grafana 4. Please test for text panels that contain both a little and a lot of text.

**Comment by jahluwalia** [comment] 2018-08-24 17:03
I did confirm this with a small image and large image. Not exactly thorough
testing, but a quick sanity test.

**Comment by IzakMarais** [comment] 2018-08-27 06:37
I just did a quick test with the latest Grafana (5.2.2). If no width and height are specified, text panels are rendered at a constant 800x400 size regardless of the amount of text content. So omitting the size entirely will not work.

Furthermore, the width and length information encoded in the panel JSON definition is not in pixel sizes. For example (note the `w` and `h` fields):
```JSON
{
  "content": "# title\n\nTest text panel rendering in grafana-reporter\n",
  "id": 2,
  "links": [],
  "mode": "markdown",
  "title": "Panel with one row",
  "type": "text",
  "gridPos": {
    "x": 6,
    "y": 0,
    "w": 9,
    "h": 14
  }
}
```
So extending the reporter to fetch the size from the dashboard definition will not work. At this stage I am going to open a Grafana ticket to discuss the options and regression since 4.6.

**Comment by nuphoff** [comment] 2018-08-28 09:05
@IzakMarais the `w` and `h` fields represent how many columns and rows the panel is in Grafana so if a Row for instance is 33px you can multiply these values. You can verify this by getting the JSON panel and then increase the rows in Grafana 1 and then again get the JSON panel information so it might still be possible to calculate the height based on the `w` and `h` fields.

**Comment by IzakMarais** [comment] 2018-08-30 06:35
@nuphoff, thanks for the suggestion. Unfortunately it looks like the pixel value of 1 row is not constant, but depends on screen size. For example, if you resize the browser window you will see that the text panel size adapts. So this sort of solution might work if we use the upper bound of that pixel value and add some safety margin.

**Comment by IzakMarais** [comment] 2018-08-30 06:36
If you want to do a pull request for this functionality it will be welcome. This change will touch the code in quite a few places and require that some of the unit tests be modified and new ones added.

**Comment by matthieuribaucourt** [comment] 2019-09-02 11:35
Hello,
I have the same issue using xubuntu + firefox + Grafana v6.3.3 running your image : https://hub.docker.com/r/izakmarais/grafana-reporter/
![Capture d’écran_2019-09-02_13-34-13](https://user-images.githubusercontent.com/49197579/64111977-43e67800-cd86-11e9-8859-5226d0dd7321.png)
![Capture d’écran_2019-09-02_13-34-45](https://user-images.githubusercontent.com/49197579/64111998-55c81b00-cd86-11e9-87cf-fe9839ce27f9.png)

**Comment by IzakMarais** [comment] 2019-09-02 13:32
@matthieuribaucourt , please add a thumbs up to https://github.com/grafana/grafana/issues/13037 if you want to see a proper fix for this issue.

**Comment by IzakMarais** [comment] 2019-10-18 06:24
Solved by enabling new grid-layout flag (-grid-layout=1).

See https://github.com/IzakMarais/reporter/issues/162#issuecomment-542528535 for an example.

**Closed by IzakMarais** 2019-10-18 06:24 UTC
